apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: review-service
        image: {{ .Values.image.repository }}
        command: [ "sleep" ]
        args: [ "infinity" ]
        ports:
        - containerPort: 8081
 